apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ninetech-db
  name: ninetech-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ninetech-db
  strategy: {}
  template:
    metadata:
      labels:
        app: ninetech-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: "ninetech"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          image: postgres:13
          name: ninetech-db
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ninetech-db
  name: ninetech-db-service
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: ninetech-db
status:
  loadBalancer: {}
